modLoader="javafml" #mandatory
loaderVersion="[38,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"

#issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId = "elementalcombat" #mandatory
version = "1.2.4.0" #mandatory

displayName = "Elemental Combat" #mandatory
#updateJSONURL = "http://myurl.me/" #optional
#displayURL = "http://example.com/" #optional
issueTrackerURL="https://github.com/Tavi007/ElementalCombat/issues" #optional
logoFile = "Icon.png" #optional. A file name (in the root of the mod JAR) containing a logo for display
credits = "Thanks goes to the Forge Forum" #optional
authors = "Tavi007" #optional

description= "This mod enhances the combat system by adding elemental and style properties to items, mobs and players. This mod also provides an API for other mods to interact with. "

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.elementalcombat]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[44,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.elementalcombat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3]"
    ordering="NONE"
    side="BOTH"
